### ISSUE TITLE
v1 issue tracker

### ISSUE THREAD

**Issue by amishshah** [crude-cards/protocols#1]
Known issues that need to be addressed:

### General
- [ ] Certain payloads may not be "efficient"

### REST
- ?

### Gateway
- ?

-----

### Done:
- [x] No way to start a game (107ebc6c4a535b40b74fb92fc569656ad7e00470)
- [x] No way to see if a game has started (107ebc6c4a535b40b74fb92fc569656ad7e00470)
- [x] There is no endpoint to fetch the rounds of a game (107ebc6c4a535b40b74fb92fc569656ad7e00470)
- [x] Timestamps aren't using ISO-8601 (d2250e0b31470884b493e3b9b87e13a6ab3e032f)
- [x] No way to set a maximum time limit for each round (73dec5fcd85cfc1f7c85435e452263d2c3fca2b7)
- [x] Cards aren't uniquely identified (69683370187a715303c1398fc8d110601a6038a3)
- [x] "`/api/games` requires authorization to search, but `/api/games/:id` does not always require authorization". No change is being made. Only users of the server would require searching for a game, whereas bots do not require search but could still watch a game without being connected to the server.
